feat: rents services update
Loopable-it/Loopable-Backend pull request #17
Opened 2023-11-23 22:25 UTC by GABRYCA

- Added new rents/<str:pk/ 'status' PATCH endpoint
- Added tests for rents status PATCH

2023-11-26 20:39 UTC, vellons commented on src/api/test/test_rents.py
> +        print(response.json())
Il print non ci serve. Lo toglierei

2023-11-26 20:41 UTC, vellons requested changes

2023-11-26 20:41 UTC, vellons commented on src/api/views.py
> +        return get_object_or_404(Rent, id=self.kwargs.get('pk'))
La funzione di destroy se non viene usata togliamola da qui e dagli url. I Rent se vogliamo cancellarli gli mettiamo lo stato "cancelled"

2023-11-26 22:46 UTC, GABRYCA commented on src/api/test/test_rents.py
> +        print(response.json())
Ok, rimosso nell'ultima commit

2023-11-26 22:46 UTC, GABRYCA commented on src/api/views.py
> +        return get_object_or_404(Rent, id=self.kwargs.get('pk'))
Ok, come temevo, rimossa la view, url, e permission

2023-11-27 20:13 UTC, vellons commented on src/api/test/test_rents.py
> +        print(response.json())
Ma sicuro che hai rimosso il print nell'ultimo commit?

2023-11-27 20:46 UTC, vellons approved these changes

2023-11-27 20:47 UTC, merged